# Lists every slide_* folder in pubspec so Flutter bundles images/audio (subdirs are not implicit).
param(
  [string]$MathRoot = (Join-Path $PSScriptRoot "..\assets\math"),
  [string]$OutFile = (Join-Path $PSScriptRoot "..\math_pubspec_assets.yaml")
)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# GENERATED by tools/generate_math_pubspec_assets.ps1")
$lines.Add("# Paste under flutter: assets: in pubspec.yaml (replace old math package lines)")

$lines.Add("    - assets/math/manifest.json")

$packagesDir = Join-Path $MathRoot "packages"
if (Test-Path $packagesDir) {
  Get-ChildItem $packagesDir -Directory | Sort-Object Name | ForEach-Object {
    $pkg = $_.Name
    Get-ChildItem $_.FullName -Directory -Filter "slide_*" | Sort-Object Name | ForEach-Object {
      $rel = "assets/math/packages/$pkg/$($_.Name)/"
      $lines.Add("    - $rel")
    }
  }
}

$lines | Set-Content -Path $OutFile -Encoding UTF8
$slideCount = $lines.Count - 3
Write-Host "Wrote manifest + $slideCount slide folders to $OutFile"
